version: '3'
services:
  server:
    image: star-angry/server
    build: .
    environment:
      GAME_PORT: 8080
      JWT_SECRET: XXXX
    volumes:
    - ./config/:/www/config/
    - ./game-data/:/www/packages/backend/dist/
    ports:
      - 7788:8080
    restart: always
